### ISSUE TITLE
Why is PACKAGE_NAME not grabbed from the PackageId msbuild property in the csproj file ?

### ISSUE THREAD

**Issue by softlion** [brandedoutcast/publish-nuget#33]
Why is PACKAGE_NAME not grabbed from the PackageId msbuild property in the csproj file ?

It is simpler.

```xml
  <PropertyGroup>
    <PackageId>Softlion.NotionSharp</PackageId>
   ...
```

**Comment by brandedoutcast** [comment]
It's just easier to set `PACKAGE_NAME` input.

Interpreting would involve checking the `csproj` file & maybe `nuspec` file & any place where `PackageId` can be configured but you're welcome to open a PR if you feel strongly about it

**Comment by softlion** [comment]
Well you are picking the version from the csproj file already

**Comment by brandedoutcast** [comment]
Yup that resulted in adding `VERSION_FILE_PATH`, `VERSION_REGEX` & `VERSION_STATIC` inputs to the action & I'm hesitant on bloating it with more such inputs if it tries to interpret the `PackageId`

Considering we don't change `PackageId` unlike the version I think it's pretty minimal effort to just add a single line to the action with `PACKAGE_NAME` what do you think?
