### ISSUE TITLE
[FEATURE] Creating a release and tag while publishing a nuget package

### ISSUE THREAD

**Issue by AnmolSinha1201** [brandedoutcast/publish-nuget#40]
We already have a feature to create a tag while publishing a package. Is it possible to also create a github release at the same time? This would be controlled by a flag, just like creating tags is.

**Comment by brandedoutcast** [comment]
Yup that's achievable using `actions/create-release` & [here's more info on how to do just that](https://github.com/brandedoutcast/publish-nuget/issues/29#issuecomment-622256432) take a look at all the comments as you might wanna modify that `if` condition based on your needs as it acts as the flag

**Comment by AnmolSinha1201** [comment]
Aah, that should cover it. Thanks!
