### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tihomir-kit** [brandedoutcast/publish-nuget#74]
Hi @brandedoutcast, are you still planning on doing anything with this project? If not, and since the project has a bunch of issues open and PR's created, would you consider letting someone else get the privileges of publishing newer versions, merging PR's and pushing this forward? 

Thanks

**Comment by lukebakken** [comment]
@brandedoutcast the RabbitMQ team is using your `publish-nuget` project and is very appreciative of the work (https://github.com/rabbitmq/rabbitmq-stream-dotnet-client). We would be willing to take over maintenance of `publish-nuget`. Thanks.

**Comment by piotrczyz** [comment]
It doesn't look like he is very active on GitHub lately :)

I suggest replacing it with dotnet commands :)

**Comment by AraHaan** [comment]
I ended up placing this action as a feature in my build-dotnet actions.

**Comment by default-kaas** [comment]
> It doesn't look like he is very active on GitHub lately :)
> 
> I suggest replacing it with dotnet commands :)

Do you have any examples?

**Comment by default-kaas** [comment]
> @brandedoutcast the RabbitMQ team is using your `publish-nuget` project and is very appreciative of the work (https://github.com/rabbitmq/rabbitmq-stream-dotnet-client). We would be willing to take over maintenance of `publish-nuget`. Thanks.

He has resume site, maybe you could find more contact information on that.
https://rohith.github.io/

**Comment by brandedoutcast** [comment]
A lot was happening in my life so I was away from GitHub & open-source

When I left, the usage metrics of this action were pretty insignificant as only a handful of people were using it mostly for their personal projects but I'm thrilled to know RabbitMQ uses it

@lukebakken I'd be happy to hand it over, just let me know whom to add as collaborators
