### ISSUE TITLE
Collaborators are welcome

### ISSUE THREAD

**Issue by brandedoutcast** [brandedoutcast/publish-nuget#80]
As mentioned in [this comment](https://github.com/brandedoutcast/publish-nuget/issues/74#issuecomment-1118387981) I was busy with handling stuff happening in my life & away from GitHub. I see there are a bunch of open issues & apologies for the inconvenience caused

I may or may not actively contribute to this action so I'm willing to hand it over & RabbitMQ seems to be interested so I'm awaiting their response for now. Once added collaborators should be able to decide on what to do with open issues & PRs

**Comment by lukebakken** [comment]
Got it! I'll find some time soon to check this project out and figure out next steps.

**Comment by AraHaan** [comment]
Having this action use only .NET commands is an option as well too, with that then they can ship their nuget.config file in their repo and it should be used automatically. I done this in my build-dotnet action (and also I needed an action that would install .NET daily builds so I also made setup-latest-dotnet).

**Comment by lukebakken** [comment]
> Alternatively projects could migrate to my build-dotnet action too

@AraHaan would you mind pointing out where that is?

**Comment by AraHaan** [comment]
Sure, it's at https://github.com/Elskom/build-dotnet/

**Comment by lukebakken** [comment]
It seems like the best path forward for this project is to direct people to alternatives:

* https://github.com/alirezanet/publish-nuget
* https://github.com/Elskom/build-dotnet
* Just use `dotnet` commands. We have adopted this method here - https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/.github/workflows/publish-nuget.yaml

@brandedoutcast I appreciate you adding myself and @Gsantomaggio to this project. I would like to update the README.md with instructions for alternatives, close issues and pull requests, and then archive this project, ensuring that it's removed from the GH actions marketplace.

**Comment by lukebakken** [comment]
Great idea.
